name: Create new release

  on:
    workflow_dispatch:
      inputs:
        name:
          description: 'Version'
          required: true
          default: 'pre-0.0.1'

        home:
          description: 'location'
          required: false
          default: 'The Octoverse'
            
        perform_deploy:
          required: true
          type: boolean

  jobs:
    say-hello:
      runs-on: ubuntu-latest
      steps:
        - name: Greet
          run: |
            echo "Hello, ${{ inputs.name }}!"
            echo "- in ${{ inputs.home }}!"
              
        - name: Deploy
          if: ${{ inputs.perform_deploy }}
          run: ./build.sh